// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zycnltrlxeggiheolxzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Y25sdHJseGVnZ2loZW9seHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODE4NzQsImV4cCI6MjA2OTg1Nzg3NH0.oda--73QylE5b2M16iN1qRrPnCT6oKrTvqd8EaVQe70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});